### ISSUE TITLE
[BUG] module 'pyhiveapi' has no attribute 'HiveApi'

### ISSUE THREAD

**Issue by samwatling** [Pyhass/Pyhiveapi#29]
**Describe the bug**
AttributeError: module 'pyhiveapi' has no attribute 'HiveApi'

**Expected behavior**
I'm using pyhiveapi per the examples on https://pyhass.github.io/pyhiveapi.docs/docs/examples/api/ - this used to work fine and I could refresh tokens using the example code. However, now, the same code returns the AttributeError shown above.

**Screenshots**

**Additional context**
pyhiveapi-0.4.2

**Comment by samwatling** [comment]
On reflection this isn't a bug - but the documentation does need updating.

**Comment by KJonline** [comment]
Updated
